# Generated by Django 3.2.7 on 2021-09-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO frontend_users (fname,lname,email)
                VALUES
                    ('Bobby','Tables','btables@gmail.com'),
                    ('Jane','Doe','jdoe@gmail.com')
            """,
            """
                DELETE FROM frontend_users
                WHERE
                    email = 'btables@gmail.com' OR
                    email = 'jdoe@gmail.com'
            """
        )
    ]
